### ISSUE TITLE
forge web start failed 

### ISSUE THREAD

**Issue by humyna** [ArcBlock/forge-js#267] opened 2019-05-09 13:22 UTC
s1.forge reset
s2.forge init 
s3.forge start 
s4.forge web start
![image](https://user-images.githubusercontent.com/2505439/57456673-8d272f00-72a0-11e9-98f1-8cdf1fae1bfb.png)
![image](https://user-images.githubusercontent.com/2505439/57456902-1179b200-72a1-11e9-9a96-bbee555045bc.png)

**Comment by wangshijun** [comment] 2019-05-10 01:55
Root cause for this issue is that developer did an incomplete setup of forge-cli and forge, and forge-cli did not enforcea forge component binary existence before executing it.

`forge web` related commands will exit if the `forge_web` binary is not found.

#271 

Closing now!

**Closed by wangshijun** 2019-05-10 01:55 UTC
Labels: forge-cli, priority/failing-test, priority/failing-user

**Comment by wangshijun** [comment] 2019-05-10 01:56
fix should be published in `@arcblock/forge-cli` v0.26.3
